apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kvmfun.fullname" . }}-env
  labels:
    {{- include "kvmfun.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- toYaml .Values.appConfig | nindent 2 }}